### ISSUE TITLE
Unity Support

### ISSUE THREAD

**Issue by SradnickDev** [ryancheung/WindowsForms.IMEHelper#2]
Hi, im trying to figure out how ime stuff works and already got some kind of a working project, still the results are bad. Do you think your helper could also work in Unity, by replacing the win forms stuff with more native calls?

**Comment by ryancheung** [comment]
You should track this PR https://github.com/MonoGame/MonoGame/pull/7118#issuecomment-667635798
We just figured out how to handle IME correctly in Windows. Basically you need handle with  IMM32 and TSF separately and switch implementation between Windows versions.
This demo repo https://github.com/ryancheung/WindowsForms.IMEHelper.Core is trying to support TSF (imm32 is already supported).

**Comment by ryancheung** [comment]
BTW, I don't use Unity and don't know how well are IME supported.

**Comment by SradnickDev** [comment]
OK thanks for the info, i'll keep an eye on the tsf stuff. Gonna try first to port this to Unity and than check out tsf.

**Comment by ryancheung** [comment]
Unity should handle all the IME stuff in native cpp for us. I don't know why it has bugs, I haven't used Unity.

Use the IMM32 implementation [here](https://github.com/MonoGame/MonoGame/blob/e61c0db5967e73408c8f69d357f8fd5561f48731/MonoGame.Framework/Platform/Windows/Input/WinFormsImeHandler.cs). It's much more complete than the demo repo.

**Comment by SradnickDev** [comment]
Hi just to provide some infos. We achieved some kind of working project https://streamable.com/iv1m3j but strange behaviour if a canidate list is open and clicking somewhere the language mode changes. Also i updated windwos to the latest version and the behaviour changed,the canidate list appears only if more chars are entered like "sa" or "ni". All done with imm32.

**Comment by ryancheung** [comment]
That's the problem when all done with IMM32 API. The approach only works well with IMM32-based IMEs, but not TSF-based IMEs, like Miscosoft PinYin.
You have to handle both IMM32 and TSF in you app/game.
I seems found the way to support TSF in C#. I'll post the TSF wrapper to github later. The wrapper is extracted from WPF Core repo.

**Comment by SradnickDev** [comment]
Do you know if some functions from imm32 are not supported on win10 ? Like ImmGetConversionList or ImmSetCompositionString, seems they just not working. I also looked into wpf tsf, would be nice to see ur tsf wrapper.

**Comment by ryancheung** [comment]
Yep. I know some functions from imm32 like `ImmSetCandidateWindow` won't work if the active IME is TSF-based, and some functions would  work but with bugs. Because we can't use IMM32 API only to handle TSF-based IME.

**Comment by ryancheung** [comment]
I looked the doc of Unity yesterday, and it shows Unity only support IME with the OS rendered Candidate Window. They don't have input events for candidates, which I can guess Unity don't handle TSF well also.

**Comment by SradnickDev** [comment]
Yeah, because of that we wanted to render the candidate window ourself and have to hook wndProc ourself too.

**Comment by ryancheung** [comment]
@SradnickDev [Here](https://github.com/ryancheung/ImeSharp) is the wrapper I just made. But there're still lots works to do, like raise text composition and result events. I'm lucky that the first version can run without crash, the Demo project show we can enable/disable ime.

**Comment by ryancheung** [comment]
Hope we can make the IME wrapper shine together :).
